"""Canonical Conduit three-lane network port defaults."""

DEFAULT_BASE_PORT = 28903
DEFAULT_DATA_PORT = DEFAULT_BASE_PORT + 1
DEFAULT_FILE_PORT = DEFAULT_BASE_PORT + 2
DEFAULT_STREAM_PORT = DEFAULT_BASE_PORT + 3
